version: '3.8'

services:
  product-api:
    image: product-api
    container_name: product-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - app-network
    depends_on:
      - product-db

  product-db:
    image: postgres:latest
    container_name: product-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
